### ISSUE TITLE
关于现在CS2服务器（To Do List）

### ISSUE THREAD

**Issue by bklol** [bklol/neko_cs2#1]
- [x] 服务器优化
- [x] 封禁系统
- [x] 服务器提示消息
- [x] 服务器皮肤插件
- [x] 贴纸插件
- [x] 手套插件
- [x] 杂项插件（探员 音乐盒）
- [ ] 35hp插件
- [ ] 回防插件
- [x] 管理员权限
- [x] 玩家rank
- [ ] 管理员菜单 指令 （快结束）
- [x] VIP功能 VIP进服通道
- [x] 玩家计分板标签

**Comment by bklol** [comment]
> > * [x]   服务器优化
> > * [x]   封禁系统
> > * [x]   服务器提示消息
> > * [x]   服务器皮肤插件
> > * [x]   贴纸插件
> > * [x]   手套插件
> > * [x]   杂项插件（探员 音乐盒）
> > * [ ]   35hp插件
> > * [ ]   回防插件
> > * [x]   管理员权限
> > * [x]   玩家rank system
> > * [ ]   管理员菜单 指令 （快结束）
> > * [ ]   VIP功能 VIP进服通道（快结束）
> > * [x]   玩家计分板标签
> 
> Yo, what happened to your cs2 log blocker, can't find it :(

i simply delete it,seems no one want it

**Comment by audiomaster99** [comment]
> i simply delete it,seems no one want it
would you mind sharing with me

**Comment by bklol** [comment]
> > i simply delete it,seems no one want it
> > would you mind sharing with me

https://github.com/bklol/cs2_log_blocker
